home:
    path:     /
    defaults: { _controller: AppBundle:Movie:home }

details:
    path:     /details/{id}
    defaults: { _controller: AppBundle:Movie:details }

#admin
admin_home:
    path:     /admin/
    defaults: { _controller: AppBundle:AdminMovie:list }

admin_movie_delete:
    path:    /admin/movies/delete/{id}
    defaults: { _controller: AppBundle:AdminMovie:delete }

admin_movie_edit:
    path:    /admin/movies/edit/{id}
    defaults: { _controller: AppBundle:AdminMovie:edit }

admin_movie_add:
    path:    /admin/movies/add/
    defaults: { _controller: AppBundle:AdminMovie:add }