home:
    path:     /
    defaults: { _controller: AppBundle:Movie:home }

details:
    path:     /details/{id}
    defaults: { _controller: AppBundle:Movie:details }

#admin
admin_home:
    path:     /admin/
    defaults: { _controller: AppBundle:AdminMovie:list }
